# Site settings
title: "Adam Hobson"
name: "Adam Hobson"                         # Needed until Issue #47 is fixed
author:
    name: "Adam Hobson"
    email: "adam@adamhobson.com"
    uri: "http://adamhobson.com/about/"
description: "Saving the World Since 1984"
url: "http://adamhobson.com"
imgurl: "/images"

# Plugins
gems:
- jekyll-feed
- jekyll-last-modified-at
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

# Outputting
permalink: /:year/:month/:day/:title
timezone: America/New_York

# Conversion
markdown: kramdown
highlighter: pygments
excerpt_separator: "\n\n"

# Markdown Processors
kramdown:
    input: GFM

# Defaults
defaults:
-
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
-
    scope:
        path: ""
        type: "pages"
    values:
        layout: "page"

# Default extension for new posts and pages
post_ext: md
page_ext: md
