# Site settings
title: Adam Hobson
email: adam@adamhobson.com
description: Saving the World Since 1984
baseurl: "" 					# the subpath of your site, e.g. /blog/
url: "http://adamhobson.com"	# the base hostname & protocol for your site
imgurl: "/images/posts/"

# Plugins
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

# Conversion
markdown: kramdown
highlighter: pygments
excerpt_separator: "\n\n"

# Outputting
permalink: /:year/:month/:day/:title/
timezone: America/New_York

# Markdown Processors
kramdown:
  input: GFM

# Defaults
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
