# Site settings
title: "Adam Hobson"
author: "Adam Hobson"
email: "adam@adamhobson.com"
description: "Saving the World Since 1984"
url: "http://adamhobson.com"                # the base hostname & protocol for your site
imgurl: "/images"

# Plugins
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

# Outputting
permalink: /:year/:month/:day/:title
timezone: America/New_York

# Conversion
markdown: kramdown
highlighter: pygments
excerpt_separator: "\n\n"

# Markdown Processors
kramdown:
    input: GFM

# Defaults
defaults:
-
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
-
    scope:
        path: ""
        type: "pages"
    values:
        layout: "page"
